[storage]
type = "S3"
bucket = "${TEST_BUCKET}"
prefix = "${TEST_PREFIX}"

[job]
num_generations = 15
terminate_at_target_gen = true
num_particles = 200

[algorithm]
tolerance_descent_percentile = 75
max_num_failures = 50
